export default {
  foodTrucks: 'Food truck',
  lateNights: 'Late night',
  healthy: 'Healthy',
  forTheSweetTooth: 'For the sweet tooth',
  forTheStudyGrind: 'For the study grind',
  openLate: 'Open late',
  parentsVisiting: 'Parents visiting',
  gotPlasteredLastNight: 'Got plastered last night',
  bars: 'Bars',
  byos: 'BYOs',
  speakeasies: 'speakeasies',
  dateNight: 'Date night',
  formals: 'Formals',
  birthdays: 'Birthdays',
  treatYourself: 'Treat yourself',
  adulting: '#Adulting',
  feelingLazy: 'Feeling lazy',
  holeInTheWall: 'Hole in the wall',
  showoffToYourFriends: 'Showing off',
  forTheGram: '#forTheGram',
  nightTime: 'nighttime',
  concerts: 'concerts',
};
